In [5]:
import os
os.chdir('/ictstr01/home/icb/fatemehs.hashemig/codes/interpretable-ssl')

In [30]:
from importlib import reload

import interpretable_ssl.evaluation.metric_helpers.embedding_metrics
import interpretable_ssl.augmenters.adata_augmenter
import interpretable_ssl.trainers.trainer
import interpretable_ssl.trainers.scproto

reload(interpretable_ssl.evaluation.metric_helpers.embedding_metrics)
reload(interpretable_ssl.augmenters.adata_augmenter)
reload(interpretable_ssl.trainers.trainer)
reload(interpretable_ssl.trainers.scproto)

In [31]:
from interpretable_ssl.trainers.scproto import *

In [32]:
t = SCProtoTrainer(debug=1, knn_method = 'diffusion')

dataset is None, loading pbmc-immune
loading pbmc-immune data
done
✅ Already subsetted to HVGs (4000 genes).

In [33]:
t.setup()

INFO - 09/14/25 11:26:58 - 0:00:00 - ============ Initialized logger ============
INFO - 09/14/25 11:26:58 - 0:00:00 - assignment_metric: dotp
                                     augmentation_type: knn
                                     base_lr: 4.8
                                     batch_removal_ratio: 0.0
                                     batch_sinkhorn: 1
                                     batch_size: 1024
                                     cell_type_key: cell_type
                                     checkpoint_freq: 30
                                     condition_key: study
                                     cvae_epochs: 0
                                     cvae_loss_scaler: 0.01
                                     cvae_reg: 0
                                     dataset: pbmc-immune
                                     dataset_cnt: 0
                                     dataset_id: pbmc-immune
                                     debug: 1
                                     decodable_prototypes: 0
                                     default_dispersion: 0.1
                                     device: cuda
                                     dimensionality_reduction: pca
                                     dist_url: env://
                                     ds_ids: range(0, 3)
                                     dump_checkpoints: /home/icb/fatemehs.hashemig/models//pbmc-immune/swav_knn_diff/checkpoints
                                     dump_name_version: 4
                                     dump_path: /home/icb/fatemehs.hashemig/models//pbmc-immune/swav_knn_diff
                                     entropy_reg: 0.0
                                     epoch_queue_starts: 0
                                     epsilon: 0.05
                                     experiment_name: swav
                                     feat_dim: 8
                                     final_lr: 0
                                     finetune_dataset_id: pbmc-immune
                                     finetune_ds: None
                                     finetuning: False
                                     fold: 0
                                     freezable_prototypes: 0
                                     freeze_batch_embedding: 0
                                     freeze_prototypes_nepochs: 20
                                     ft_epochs: 0
                                     hard_clustering: 0
                                     hidden_dim: 64
                                     hidden_mlp: 1024
                                     input_dim: 4000
                                     job_name: swav_knn_diff/None
                                     k_neighbors: 50
                                     knn_method: diffusion
                                     knn_similarity: cosine
                                     l2norm: 1
                                     latent_dims: 8
                                     linear_eval: False
                                     local_rank: 0
                                     longest_path: 1
                                     loss_type: cross_entropy
                                     lr_schedule:
                                     mask_probability: 0.2
                                     max_scale_crops: [1]
                                     min_scale_crops: [0.14]
                                     model:
                                     model_name_version: 7
                                     model_type: gm
                                     model_version: 1
                                     multi_layer_protos: 0
                                     n_components: 50
                                     nmb_crops: [4]
                                     nmb_prototypes: 300
                                     no_data: False
                                     no_sinkhorn: 0
                                     num_prototypes: 300
                                     only_eval: False
                                     optimizer:
                                     original_ref: pbmc-immune
                                     params: {'dataset_id': 'pbmc-immune', 'model_name_version': 7, 'num_prototypes': 300, 'hidden_dim': 64, 'latent_dims': 8, 'experiment_name': 'swav', 'condition_key': 'study', 'cell_type_key': 'cell_type', 'linear_eval': False, 'only_eval': False, 'use_early_stopping': False, 'training_type': 'pretrain_encoder', 'pretrain_dataset_id': 'hlca', 'finetune_dataset_id': 'pbmc-immune', 'dump_name_version': 4, 'nmb_crops': [4], 'augmentation_type': 'knn', 'size_crops': [224], 'min_scale_crops': [0.14], 'max_scale_crops': [1], 'views_for_assign': [0, 1], 'sinkhorn_iterations': 3, 'feat_dim': 8, 'cvae_reg': 0, 'dist_url': 'env://', 'world_size': 1, 'rank': 0, 'local_rank': 0, 'checkpoint_freq': 30, 'umap_checkpoint_freq': 10, 'scib_freq': 10, 'save_scib': 1, 'use_fp16': False, 'sync_bn': 'pytorch', 'syncbn_process_group_size': 8, 'seed': 31, 'model': '', 'optimizer': '', 'lr_schedule': '', 'queue': None, 'train_loader': '', 'training_stats': '', 'device': 'cuda', 'prot_decoding_loss_scaler': 0.0, 'hidden_mlp': 1024, 'swav_dim': 64, 'use_projector': False, 'model_version': 1, 'train_decoder': False, 'longest_path': 1, 'dimensionality_reduction': 'pca', 'k_neighbors': 50, 'job_name': '', 'no_data': 'False', 'freezable_prototypes': 0, 'prot_init': 'kmeans', 'prot_emb_sim_reg': 0.0, 'loss_type': 'cross_entropy', 'decodable_prototypes': 0, 'save_temp_res': 1, 'temp_res_path': 'temp-res', 'n_components': 50, 'supervised_ratio': 0.1, 'multi_layer_protos': 0, 'batch_removal_ratio': 0.0, 'use_bknn': 0, 'freeze_batch_embedding': 0, 'batch_sinkhorn': 1, 'weighted_batch': 0, 'knn_similarity': 'cosine', 'recon_loss': 'mse', 'no_sinkhorn': 0, 'wandb_sweep': 0, 'sweep_id': -1, 'mask_probability': 0.2, 'default_dispersion': 0.1, 'fold': 0, 'spatial': 0, 'use_the_queue': 0, 'entropy_reg': 0.0, 'dataset_cnt': 0, 'study_id': '', 'l2norm': 1, 'use_rbf': 1, 'assignment_metric': 'dotp', 'pretraining_epochs': 50, 'ft_epochs': 0, 'cvae_epochs': 0, 'cvae_loss_scaler': 0.01, 'propagation_reg': 1, 'model_type': 'gm', 'workers': 1, 'wd': 1e-06, 'final_lr': 0, 'warmup_epochs': 10, 'start_warmup': 0, 'batch_size': 1024, 'base_lr': 4.8, 'freeze_prototypes_nepochs': 20, 'hard_clustering': 0, 'temperature': 0.1, 'epsilon': 0.05, 'epoch_queue_starts': 0, 'queue_length': 0, 'use_counts': 1, 'knn_method': 'diffusion', 'debug': 1}
                                     partial_ref: None
                                     pretrain_dataset_id: hlca
                                     pretraining_epochs: 50
                                     propagation_reg: 1
                                     prot_decoding_loss_scaler: 0.0
                                     prot_emb_sim_reg: 0.0
                                     prot_init: kmeans
                                     query: pbmc-immune
                                     queue: {}
                                     queue_length: 0
                                     rank: 0
                                     recon_loss: mse
                                     ref: pbmc-immune
                                     save_scib: 1
                                     save_temp_res: 1
                                     scib_freq: 10
                                     seed: 31
                                     sinkhorn_iterations: 3
                                     size_crops: [224]
                                     spatial: 0
                                     start_warmup: 0
                                     study_id:
                                     supervised_ratio: 0.1
                                     swav_dim: 64
                                     sweep_id: -1
                                     sync_bn: pytorch
                                     syncbn_process_group_size: 8
                                     temp_res_path: temp-res
                                     temperature: 0.1
                                     train_augmentation: knn
                                     train_decoder: False
                                     train_loader:
                                     training_stats:
                                     training_type: pretrain_encoder
                                     transfer_learning_mode: False
                                     umap_checkpoint_freq: 10
                                     use_bknn: 0
                                     use_counts: 1
                                     use_early_stopping: False
                                     use_fp16: False
                                     use_projector: False
                                     use_projector_out: False
                                     use_rbf: 1
                                     use_the_queue: 0
                                     views_for_assign: [0, 1]
                                     wandb_sweep: 0
                                     warmup_epochs: 10
                                     wd: 1e-06
                                     weighted_batch: 0
                                     workers: 1
                                     world_size: 1
INFO - 09/14/25 11:26:58 - 0:00:00 - The experiment will be stored in /home/icb/fatemehs.hashemig/models//pbmc-immune/swav_knn_diff


INFO - 09/14/25 11:26:58 - 0:00:00 - Building model done. with prot init kmeans

Embedding dictionary:
 	Num conditions: [3]
 	Embedding dim: [10]
Encoder Architecture:
	Input Layer in, out and cond: 4000 64 10
	Mean/Var Layer in/out: 64 8
Decoder Architecture:
	First Layer in, out and cond:  8 64 10
	Output Layer in/out:  64 4000

INFO - 09/14/25 11:26:59 - 0:00:01 - Building optimizer done.

True <class 'anndata._core.views.ArrayView'> 4044.0
True <class 'anndata._core.views.ArrayView'> 3167.0

In [34]:
len(t.train_loader)

9

In [35]:
t.debug=0
t.save_checkpoint(1)

In [41]:
pd.read_csv('/home/icb/fatemehs.hashemig/models//pbmc-immune/swav_knn_diff/scgraph.csv')

             Unnamed: 0  Rank-PCA  Corr-PCA  Corr-Weighted
0  swav_knn_diff_mc_pca  0.848666  0.941326       0.893627
1         swav_knn_diff  0.470772  0.706247       0.452508

In [40]:
pd.read_csv('/home/icb/fatemehs.hashemig/models//pbmc-immune/swav/scgraph.csv')

    Unnamed: 0  Rank-PCA  Corr-PCA  Corr-Weighted
0  swav_mc_pca  0.893882  0.958255       0.914134
1         swav  0.482537  0.718302       0.471854

In [14]:
pd.read_csv('/home/icb/fatemehs.hashemig/models//pbmc-immune/swav_knn_diff/scib.csv')

,Embedding,Isolated labels,KMeans NMI,KMeans ARI,Silhouette label,cLISI,Silhouette batch,iLISI,KBET,Graph connectivity,PCR comparison,Batch correction,Bio conservation,Total
0,swav_knn_diff_mc_pca,0.501285,0.472391,0.157737,0.427407,0.931081,0.731095,0.264572,0.902583,0.764076,0.000000,0.532465,0.49798,0.511774
1,swav_knn_diff,0.549258,0.652293,0.378822,0.580366,0.992660,0.819347,0.216750,0.254685,0.886245,0.929077,0.621221,0.63068,0.626896

In [1]:
import jax, subprocess, sys

# Force JAX 32-bit in parent
jax.config.update("jax_enable_x64", False)
print("PARENT before subprocess:", jax.config.read("jax_enable_x64"))

PARENT before subprocess: False

In [4]:
import jax, subprocess, sys

jax.config.update("jax_enable_x64", False)
print("PARENT before:", jax.config.read("jax_enable_x64"))

subprocess.run([sys.executable, "-m", "child"], check=True)

print("PARENT after :", jax.config.read("jax_enable_x64"))

PARENT before: False
CHILD: True
PARENT after : False