In [1]:
import os
os.chdir('/ictstr01/home/icb/fatemehs.hashemig/codes/interpretable-ssl')

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [2]:
import pandas as pd
import numpy as np

def show(df):
    def style_col(col):
        vals = col.values.astype(float)
        order = np.argsort(-vals)  # descending
        styles = [""] * len(col)
        if len(order) > 0:
            styles[order[0]] = "font-weight: bold"
        if len(order) > 1:
            styles[order[1]] = "text-decoration: underline"
        return styles

    return df.style.apply(style_col, axis=0)

In [3]:
import interpretable_ssl.datasets.dataset_configs 
from importlib import reload
reload(interpretable_ssl.datasets.dataset_configs)

In [127]:
from interpretable_ssl.evaluation.metric_helpers.embedding_tables import *
from interpretable_ssl.datasets.dataset_configs import *
from interpretable_ssl.evaluation.dropout_recovery import *

ds_id = 's28nsc'
df, dfs = load_tb(ds_id)

ad, bk, lk, n = load_ds(ds_id)

rare_ct = get_rare(labels=ad.obs[lk])
ct= list(ad.obs[lk].unique())
dfs.keys()

100%|██████████| 49/49 [00:41<00:00,  1.17it/s]

dict_keys(['avg_purity_celltypes', 'avg_purity_fibroblast_subclusters', 'ct_niche_f1', 'avg_purity_niches_3D', 'purity_stats', 'mc_marker_f1', 'new_niches', 'mc_marker_coverage', 'avg_purity_EMT_niche', 'mc_mes', 'avg_purity_niches_2D', 'mc_quality_summary', 'niches_2D_f1', 'majority_f1', 'scgraph', 'kr_niches', 'ct_niche_jaccard', 'ct_niche_rbo', 'mc_quality', 'enriched_niches', 'sample_marker_f1', 'sample_marker_coverage', 'stats', 'celltypes_f1', 'kv_niches', 'all_purities', 'ct_niche_sill_micro', 'ct_niche_sill', 'mc_purity_celltypes', 'dge_kendall', 'EMT_niche_f1', 'dge_jaccard', 'dge_all', 'dge_rbo'])

In [144]:
show(dfs['ct_niche_sill'])

In [152]:
ad[ad.obs[lk] == 'Tumor cells'].obs['niches_2D'].value_counts()

niches_2D
Desmoplastic stroma         13407
Tumor surface               12004
Vascular stroma              7167
Macrophage islands           5465
T cell aggregates            5430
Tumor core                   4629
Airways                      4085
Excluded                     2328
Alveolar spaces              2248
Smooth muscle structures     1660
Name: count, dtype: int64

In [148]:
df = dfs['ct_niche_sill_micro']
ct = 'Tumor cells'
cols = [c for c in df.columns if c.endswith(ct)]
show(df[cols])

In [134]:
model_str = 'scpoli|seacell|swav_ds-s28n_NP700_aff-ckcw_kl0.0_recon0.0_lpr1.0_cvae_e10_finetune0_p0.0_v29|scpoli|swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_v29|swav_ds-s28n_NP700_aff-ckpw_kl0.0_recon0.0_lpr1.0_cvae_e10_finetune0_p0.0_v29'
df = dfs['kr_niches']
eps = 1e-2
df = df[df.index.str.contains(model_str + '|' + models_str)]
df = df.loc[:, (df.abs() > eps).any(axis=0)]

show(df)

In [141]:
'swav_ds-s28n_NP700_aff-ckpw_kl0.0_lpr1.0_cvae_e10_finetune0_p0.0_v29' == 'swav_ds-s28n_NP700_aff-ckpw_kl0.0_lpr1.0_cvae_e10_finetune0_p0.0_v29'

True

In [142]:
df = dfs['new_niches']
eps = 1e-2
# df = df[df.index.str.contains(model_str + '|' + models_str)]
df = df.loc[:, (df.abs() > eps).any(axis=0)]
df['avg'] = df.mean(axis=1)
df = df.sort_values('avg', ascending=False)
show(df)

/tmp/ipykernel_3776631/431811511.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['avg'] = df.mean(axis=1)

In [136]:
df = dfs['new_niches']
eps = 1e-2
df = df[df.index.str.contains(model_str + '|' + models_str)]
df = df.loc[:, (df.abs() > eps).any(axis=0)]

show(df)

In [137]:
df = dfs['stats']
df = df[df.index.str.contains(model_str + '|' + models_str)]
df = df.loc[:, (df.abs() > eps).any(axis=0)]

show(df)

In [48]:
for k in dfs.keys():
    if not(k.endswith('f1')):
        print(k)

avg_purity_celltypes
avg_purity_fibroblast_subclusters
avg_purity_niches_3D
purity_stats
new_niches
mc_marker_coverage
avg_purity_EMT_niche
mc_mes
avg_purity_niches_2D
mc_quality_summary
scgraph
kr_niches
ct_niche_jaccard
ct_niche_rbo
mc_quality
enriched_niches
sample_marker_coverage
stats
kv_niches
all_purities
mc_purity_celltypes
dge_kendall
dge_jaccard
dge_all
dge_rbo

In [ ]:
# I want to show that scproto cluster cells based on context similarity within their cell type
# so we can find niche labels of a cell of a cell type [cluster - f1 score]
# we can find niche related genes in each cell type

In [47]:
# ct_niche_f1: scpoli > scproto >> seacell
# niches_2D_f1: scpoli > scproto >> seacell
# celltypes_f1: scpoli > scproto >> seacell

# [ I have no idea why seacell is this much bad in f1 tasks]

# avg_purity_celltypes: seacell > scproto >> scpoli
# avg_purity_fibroblast_subclusters: scproto > scpoli > seacell
# avg_purity_niches_2D: scproto > seacell > scpoli

In [74]:
m1 = 'swav_ds-s28n_NP700_aff-ckpw_kl0.0_recon0.0_lpr1.0_cvae_e10_finetune0_p0.0_v29'
m2 =  'swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_lpr1.0_finetune0_p0.0_v29'
m3 = 'swav_ds-s28n_NP700_aff-ckcw_kl0.0_finetune0_p0.0_v29'
m4 = 'swav_ds-s28n_NP700_aff-ckpw_kl0.0_finetune0_p0.0_v29'
models = [m1, m2, m3, m4]
model_str = '|'.join(models)

In [ ]:
ckcw

In [95]:
dfs['stats'].sort_values('unused_proto')

,epsilon,unused_proto,unused_proto_ratio,cov_niches_2D,cov_celltypes,cov_section,cov_celltypes_niches_2D,cov_EMT_niche
swav_ds-s28n_NP700_aff-c4_kl0.0_finetune0_temp0.84_eps0.84_sink_itr3_p0.0_v29,0.84,0,0.000000,1.0,1.000000,1.0,0.302857,NaN
swav_ds-s28n_NP700_aff-c4_finetune0_temp0.84_eps0.84_p0.0_v29,0.84,0,0.000000,1.0,0.944444,1.0,0.331429,NaN
seacell,NaN,0,0.000000,1.0,1.000000,1.0,0.262857,1.0
swav_ds-s28n_NP700_aff-ckpw_kl0.0_lpr1.0_cvae_e10_finetune0_p0.0_v29,0.05,0,0.000000,1.0,1.000000,1.0,0.480000,NaN
swav_ds-s28n_NP700_aff-c4_kl0.0_finetune0_temp0.84_eps0.45_p0.0_v29,0.45,0,0.000000,1.0,1.000000,1.0,0.400000,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_lpr1.0_finetune0_sink_itr3_p0.0_v29,0.05,2,0.002857,1.0,1.000000,1.0,0.617143,NaN
swav_ds-s28n_NP700_aff-ckpw_kl0.0_recon0.0_lpr1.0_cvae_e10_finetune0_p0.0_v29,0.05,3,0.004286,1.0,1.000000,1.0,0.514286,NaN
swav_ds-s28n_NP700_aff-c4_kl0.0_finetune0_temp0.84_eps0.84_p0.0_v29,0.84,3,0.004286,1.0,1.000000,1.0,0.320000,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_lpr1.0_finetune0_p0.0_v29,0.05,3,0.004286,1.0,1.000000,1.0,0.622857,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.6_eps0.3_sink_itr3_p0.0_v29,0.30,3,0.004286,1.0,1.000000,1.0,0.422857,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_lpr0.5_finetune0_sink_itr3_p0.0_v29,0.05,10,0.014286,1.0,1.000000,1.0,0.622857,NaN
swav_ds-s28n_NP700_aff-ckcw_kl0.0_lpr1.0_cvae_e10_finetune0_p0.0_v29,0.05,11,0.015714,1.0,1.000000,1.0,0.474286,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_lpr0.5_finetune0_p0.0_v29,0.05,24,0.034286,1.0,1.000000,1.0,0.640000,NaN
swav_ds-s28n_NP700_aff-c5_finetune0_temp0.6_eps0.3_p0.0_v29,0.30,27,0.038571,1.0,1.000000,1.0,0.434286,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.6_eps0.6_p0.0_v29,0.60,31,0.044286,1.0,0.944444,1.0,0.342857,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.6_eps0.3_p0.0_v29,0.30,39,0.055714,1.0,1.000000,1.0,0.411429,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.2_eps0.1_sink_itr3_p0.0_v29,0.10,42,0.060000,1.0,1.000000,1.0,0.542857,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_finetune0_temp0.6_eps0.3_sink_itr3_p0.0_v29,0.30,46,0.065714,1.0,1.000000,1.0,0.360000,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_finetune0_temp0.2_eps0.1_sink_itr3_p0.0_v29,0.10,183,0.261429,1.0,1.000000,1.0,0.508571,NaN
swav_ds-s28n_NP700_aff-c5_finetune0_temp0.2_eps0.1_p0.0_v29,0.10,291,0.415714,1.0,1.000000,1.0,0.594286,NaN
swav_ds-s28n_NP700_aff-c4_kl0.0_recon0.0_finetune0_temp0.84_eps0.84_sink_itr3_p0.0_v29,0.84,293,0.418571,1.0,1.000000,1.0,0.320000,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_finetune0_sink_itr3_p0.0_v29,0.05,308,0.440000,1.0,1.000000,1.0,0.617143,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.2_eps0.1_p0.0_v29,0.10,313,0.447143,1.0,1.000000,1.0,0.582857,NaN
swav_ds-s28n_NP700_aff-c4_kl0.0_finetune0_p0.0_v29,0.05,460,0.657143,1.0,1.000000,1.0,0.605714,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_p0.0_v29,0.05,469,0.670000,1.0,1.000000,1.0,0.582857,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_v29,0.05,478,0.682857,1.0,1.000000,1.0,0.588571,NaN
swav_ds-s28n_NP700_aff-ckpw_kl0.0_finetune0_p0.0_v29,0.05,499,0.712857,1.0,1.000000,1.0,0.594286,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_cvae_e10_finetune0_p0.0_v29,0.05,519,0.741429,1.0,1.000000,1.0,0.525714,NaN
swav_ds-s28n_NP700_aff-ckpw_kl0.0_cvae_e10_finetune0_p0.0_v29,0.05,522,0.745714,1.0,1.000000,1.0,0.520000,NaN
swav_ds-s28n_NP700_aff-ckcw_kl0.0_cvae_e10_finetune0_p0.0_v29,0.05,535,0.764286,1.0,1.000000,1.0,0.514286,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_cvae_e5_finetune0_p0.0_v29,0.05,543,0.775714,1.0,1.000000,1.0,0.514286,NaN
swav_ds-s28n_NP700_aff-ckcw_kl0.0_finetune0_p0.0_v29,0.05,565,0.807143,1.0,0.944444,1.0,0.582857,NaN

In [93]:
# .sort_values('f1_macro', ascending = False)
df = dfs['avg_purity_niches_2D']
metric = "avg"   # change
k = 10

top = df.sort_values(metric, ascending=False)
keep = top.head(k).index.union(
    top.index[top.index.str.contains("scpoli|seacell", case=False, regex=True)]
)

df = df.loc[keep]

show(df)

In [21]:
dfs['ct_niche_rbo']

,Cytotoxic T cells,Tumor cells,Respiratory epithelium,Macrophages,Fibroblasts,Monocytes,Cycling immune cells,Vascular endothelium,Regulatory T cells,Mast cells,Smooth muscle cells,Pericytes,Plasma cells,Lymphatic endothelial cells,Dendritic cells,Alveolar cells,B cells,Basal epithelial cells
swav_ds-s28n_NP700_aff-c4_kl0.0_recon0.0_finetune0_temp0.84_eps0.84_sink_itr3_p0.0_v29,0.222222,0.000000,0.000,0.333333,0.222222,0.333333,0.222222,0.222222,0.111111,0.111111,0.000000,0.333333,0.375,0.222222,0.375,0.250,0.375,0.142857
swav_ds-s28n_NP700_aff-c4_kl0.0_finetune0_temp0.84_eps0.84_p0.0_v29,0.111111,0.111111,0.000,0.222222,0.555556,0.444444,0.000000,0.222222,0.111111,0.444444,0.000000,0.111111,0.250,0.333333,0.125,0.500,0.125,0.142857
swav_ds-s28n_NP700_aff-c4_kl0.0_finetune0_temp0.84_eps0.84_sink_itr3_p0.0_v29,0.111111,0.111111,0.000,0.000000,0.333333,0.333333,0.000000,0.222222,0.111111,0.222222,0.000000,0.111111,0.375,0.555556,0.125,0.500,0.125,0.142857
swav_ds-s28n_NP700_aff-c4_finetune0_temp0.84_eps0.84_p0.0_v29,0.222222,0.111111,0.000,0.222222,0.444444,0.222222,0.000000,0.222222,0.111111,0.444444,0.000000,0.333333,0.375,0.333333,0.375,0.250,0.375,0.000000
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.2_eps0.1_p0.0_v29,0.333333,0.111111,0.125,0.333333,0.777778,0.333333,0.444444,0.222222,0.666667,0.000000,0.111111,0.222222,0.375,0.111111,0.375,0.000,0.000,0.285714
swav_ds-s28n_NP700_aff-c5_finetune0_temp0.2_eps0.1_p0.0_v29,0.333333,0.222222,0.125,0.555556,0.777778,0.333333,0.444444,0.222222,0.666667,0.000000,0.111111,0.111111,0.375,0.111111,0.250,0.000,0.000,0.428571
seacell,0.444444,0.333333,0.000,0.444444,0.555556,0.222222,0.111111,0.333333,0.222222,0.000000,0.000000,0.000000,0.125,0.111111,0.125,0.000,0.000,0.000000
scpoli_ds-s28n_NP700_lswav0.0_finetune0_laff0.0_v24,0.444444,0.222222,0.000,0.666667,0.888889,0.444444,0.111111,0.222222,0.333333,0.555556,0.333333,0.333333,0.250,0.333333,0.250,0.500,0.250,0.285714
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.2_eps0.1_sink_itr3_p0.0_v29,0.444444,0.111111,0.125,0.444444,0.777778,0.666667,0.444444,0.222222,0.333333,0.111111,0.222222,0.111111,0.250,0.000000,0.250,0.125,0.250,0.142857
swav_ds-s28n_NP700_aff-c4_kl0.0_finetune0_temp0.84_eps0.45_p0.0_v29,0.111111,0.111111,0.125,0.222222,0.333333,0.333333,0.000000,0.222222,0.222222,0.222222,0.111111,0.111111,0.250,0.222222,0.250,0.375,0.125,0.000000
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.6_eps0.3_p0.0_v29,0.333333,0.111111,0.250,0.444444,0.555556,0.444444,0.111111,0.222222,0.222222,0.000000,0.111111,0.111111,0.125,0.111111,0.125,0.375,0.000,0.142857
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_p0.0_v29,0.333333,0.222222,0.000,0.777778,0.777778,0.333333,0.666667,0.111111,0.333333,0.000000,0.333333,0.222222,0.500,0.000000,0.375,0.000,0.125,0.142857
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.6_eps0.3_sink_itr3_p0.0_v29,0.222222,0.111111,0.125,0.333333,0.444444,0.444444,0.222222,0.222222,0.111111,0.111111,0.222222,0.222222,0.125,0.222222,0.125,0.250,0.125,0.142857
swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_finetune0_temp0.2_eps0.1_sink_itr3_p0.0_v29,0.222222,0.111111,0.125,0.777778,0.555556,0.333333,0.444444,0.222222,0.222222,0.222222,0.111111,0.222222,0.250,0.111111,0.250,0.250,0.000,0.285714
swav_ds-s28n_NP700_aff-c5_finetune0_temp0.6_eps0.3_p0.0_v29,0.111111,0.111111,0.250,0.444444,0.555556,0.444444,0.222222,0.222222,0.222222,0.000000,0.111111,0.111111,0.125,0.111111,0.125,0.250,0.000,0.142857
swav_ds-s28n_NP700_aff-c4_kl0.0_finetune0_p0.0_v29,0.333333,0.111111,0.250,0.555556,0.777778,0.444444,0.555556,0.222222,0.333333,0.000000,0.111111,0.111111,0.375,0.000000,0.375,0.000,0.000,0.142857
swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_finetune0_temp0.6_eps0.3_sink_itr3_p0.0_v29,0.111111,0.111111,0.125,0.222222,0.333333,0.444444,0.333333,0.222222,0.222222,0.111111,0.111111,0.222222,0.125,0.222222,0.250,0.125,0.000,0.142857
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.6_eps0.6_p0.0_v29,0.111111,0.111111,0.125,0.333333,0.555556,0.444444,0.000000,0.222222,0.111111,0.111111,0.111111,0.222222,0.375,0.333333,0.250,0.250,0.125,0.142857

In [20]:
dfs['all_purities'].drop('avg', axis = 1).sort_values('joint_purity', ascending = False)

,Cytotoxic T cells_npur,Tumor cells_npur,Respiratory epithelium_npur,Macrophages_npur,Fibroblasts_npur,Monocytes_npur,Cycling immune cells_npur,Vascular endothelium_npur,Regulatory T cells_npur,Mast cells_npur,Smooth muscle cells_npur,Pericytes_npur,Plasma cells_npur,Lymphatic endothelial cells_npur,Dendritic cells_npur,Alveolar cells_npur,B cells_npur,Basal epithelial cells_npur,celltype_purity,joint_purity
swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_finetune0_temp0.2_eps0.1_sink_itr3_p0.0_v29,0.5,0.538462,1.0,0.500000,0.500000,0.500000,0.500000,0.666667,0.500000,1.000,0.652015,0.750000,0.606061,0.666667,0.666667,0.822222,0.500000,1.0,0.822798,0.507146
swav_ds-s28n_NP700_aff-c5_finetune0_temp0.2_eps0.1_p0.0_v29,0.5,0.521739,1.0,0.500000,0.465649,0.500000,0.500000,0.666667,0.633333,1.000,0.747449,0.788462,0.625000,0.666667,0.645833,0.833333,0.833333,1.0,0.798546,0.505304
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.2_eps0.1_p0.0_v29,0.5,0.538462,1.0,0.492857,0.454545,0.500000,0.500000,0.675676,0.666667,0.875,0.736126,0.750000,0.638710,0.666667,0.683333,0.831989,1.000000,1.0,0.793175,0.498620
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_p0.0_v29,0.5,0.500000,1.0,0.452381,0.473669,0.633333,0.666667,0.528689,0.574777,0.500,0.586207,1.000000,0.640163,0.666667,0.578986,0.887130,0.875000,1.0,0.766263,0.484869
seacell,0.5,0.536585,1.0,0.459052,0.478854,0.500000,0.516667,0.666667,1.000000,1.000,0.681818,0.823529,0.924242,1.000000,0.928571,1.000000,1.000000,1.0,0.839815,0.457883
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.2_eps0.1_sink_itr3_p0.0_v29,0.5,0.517318,1.0,0.447632,0.500000,0.500000,0.500000,0.693750,0.625000,1.000,0.666667,1.000000,0.714286,0.666667,0.700000,1.000000,1.000000,1.0,0.803949,0.451768
swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_finetune0_temp0.6_eps0.3_sink_itr3_p0.0_v29,0.5,0.530090,1.0,0.470588,0.500000,0.500000,0.500000,0.653333,0.500000,1.000,0.666667,0.801235,0.707265,0.732143,0.714286,1.000000,1.000000,1.0,0.810038,0.450102
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.6_eps0.6_p0.0_v29,0.5,0.533680,1.0,0.444444,0.500000,0.500000,0.500000,0.666667,0.543478,1.000,0.600000,0.874510,0.750000,1.000000,0.666667,1.000000,0.666667,1.0,0.797941,0.448536
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.6_eps0.3_p0.0_v29,0.5,0.531582,1.0,0.428571,0.500000,0.500000,0.500000,0.666667,0.533333,1.000,0.600000,0.792641,0.750000,0.916667,0.666667,1.000000,1.000000,1.0,0.801026,0.447990
swav_ds-s28n_NP700_aff-c5_finetune0_temp0.6_eps0.3_p0.0_v29,0.5,0.531915,1.0,0.428571,0.490654,0.500000,0.500000,0.666667,0.600000,1.000,0.659574,0.791024,0.816667,0.816667,0.630682,1.000000,1.000000,1.0,0.800071,0.432351
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.6_eps0.3_sink_itr3_p0.0_v29,0.5,0.539130,1.0,0.442623,0.454545,0.500000,0.571429,0.750000,0.666667,1.000,0.666667,1.000000,0.750000,1.000000,0.738636,1.000000,1.000000,1.0,0.777463,0.390580

In [15]:
df = dfs['all_purities']
df['avg'] = dfs['all_purities'].drop(['celltype_purity', 'joint_purity'], axis=1).mean(axis = 1)
df.sort_values('joint_purity', ascending = False)

,Cytotoxic T cells_npur,Tumor cells_npur,Respiratory epithelium_npur,Macrophages_npur,Fibroblasts_npur,Monocytes_npur,Cycling immune cells_npur,Vascular endothelium_npur,Regulatory T cells_npur,Mast cells_npur,...,Pericytes_npur,Plasma cells_npur,Lymphatic endothelial cells_npur,Dendritic cells_npur,Alveolar cells_npur,B cells_npur,Basal epithelial cells_npur,celltype_purity,joint_purity,avg
swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_finetune0_temp0.2_eps0.1_sink_itr3_p0.0_v29,0.5,0.538462,1.0,0.500000,0.500000,0.500000,0.500000,0.666667,0.500000,1.000,...,0.750000,0.606061,0.666667,0.666667,0.822222,0.500000,1.0,0.822798,0.507146,0.659376
swav_ds-s28n_NP700_aff-c5_finetune0_temp0.2_eps0.1_p0.0_v29,0.5,0.521739,1.0,0.500000,0.465649,0.500000,0.500000,0.666667,0.633333,1.000,...,0.788462,0.625000,0.666667,0.645833,0.833333,0.833333,1.0,0.798546,0.505304,0.690415
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.2_eps0.1_p0.0_v29,0.5,0.538462,1.0,0.492857,0.454545,0.500000,0.500000,0.675676,0.666667,0.875,...,0.750000,0.638710,0.666667,0.683333,0.831989,1.000000,1.0,0.793175,0.498620,0.695002
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_p0.0_v29,0.5,0.500000,1.0,0.452381,0.473669,0.633333,0.666667,0.528689,0.574777,0.500,...,1.000000,0.640163,0.666667,0.578986,0.887130,0.875000,1.0,0.766263,0.484869,0.670204
seacell,0.5,0.536585,1.0,0.459052,0.478854,0.500000,0.516667,0.666667,1.000000,1.000,...,0.823529,0.924242,1.000000,0.928571,1.000000,1.000000,1.0,0.839815,0.457883,0.778666
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.2_eps0.1_sink_itr3_p0.0_v29,0.5,0.517318,1.0,0.447632,0.500000,0.500000,0.500000,0.693750,0.625000,1.000,...,1.000000,0.714286,0.666667,0.700000,1.000000,1.000000,1.0,0.803949,0.451768,0.723962
swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_finetune0_temp0.6_eps0.3_sink_itr3_p0.0_v29,0.5,0.530090,1.0,0.470588,0.500000,0.500000,0.500000,0.653333,0.500000,1.000,...,0.801235,0.707265,0.732143,0.714286,1.000000,1.000000,1.0,0.810038,0.450102,0.709756
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.6_eps0.6_p0.0_v29,0.5,0.533680,1.0,0.444444,0.500000,0.500000,0.500000,0.666667,0.543478,1.000,...,0.874510,0.750000,1.000000,0.666667,1.000000,0.666667,1.0,0.797941,0.448536,0.708117
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.6_eps0.3_p0.0_v29,0.5,0.531582,1.0,0.428571,0.500000,0.500000,0.500000,0.666667,0.533333,1.000,...,0.792641,0.750000,0.916667,0.666667,1.000000,1.000000,1.0,0.801026,0.447990,0.715896
swav_ds-s28n_NP700_aff-c5_finetune0_temp0.6_eps0.3_p0.0_v29,0.5,0.531915,1.0,0.428571,0.490654,0.500000,0.500000,0.666667,0.600000,1.000,...,0.791024,0.816667,0.816667,0.630682,1.000000,1.000000,1.0,0.800071,0.432351,0.718468
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.6_eps0.3_sink_itr3_p0.0_v29,0.5,0.539130,1.0,0.442623,0.454545,0.500000,0.571429,0.750000,0.666667,1.000,...,1.000000,0.750000,1.000000,0.738636,1.000000,1.000000,1.0,0.777463,0.390580,0.754428

In [9]:
df = dfs['all_purities']
show(df.sort_values('joint_purity', ascending=False))

In [11]:
dfs['stats'].sort_values('unused_proto')

,epsilon,unused_proto,unused_proto_ratio,cov_niches_2D,cov_celltypes,cov_section,cov_celltypes_niches_2D,cov_EMT_niche
swav_ds-s28n_NP700_aff-c4_kl0.0_finetune0_temp0.84_eps0.45_p0.0_v29,0.45,0,0.000000,1.0,1.000000,1.0,0.400000,NaN
swav_ds-s28n_NP700_aff-c4_kl0.0_finetune0_temp0.84_eps0.84_sink_itr3_p0.0_v29,0.84,0,0.000000,1.0,1.000000,1.0,0.302857,NaN
swav_ds-s28n_NP700_aff-c4_finetune0_temp0.84_eps0.84_p0.0_v29,0.84,0,0.000000,1.0,0.944444,1.0,0.331429,NaN
seacell,NaN,0,0.000000,1.0,1.000000,1.0,0.262857,1.0
swav_ds-s28n_NP700_aff-c4_kl0.0_finetune0_temp0.84_eps0.84_p0.0_v29,0.84,3,0.004286,1.0,1.000000,1.0,0.320000,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.6_eps0.3_sink_itr3_p0.0_v29,0.30,3,0.004286,1.0,1.000000,1.0,0.422857,NaN
swav_ds-s28n_NP700_aff-c5_finetune0_temp0.6_eps0.3_p0.0_v29,0.30,27,0.038571,1.0,1.000000,1.0,0.434286,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.6_eps0.6_p0.0_v29,0.60,31,0.044286,1.0,0.944444,1.0,0.342857,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.6_eps0.3_p0.0_v29,0.30,39,0.055714,1.0,1.000000,1.0,0.411429,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.2_eps0.1_sink_itr3_p0.0_v29,0.10,42,0.060000,1.0,1.000000,1.0,0.542857,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_finetune0_temp0.6_eps0.3_sink_itr3_p0.0_v29,0.30,46,0.065714,1.0,1.000000,1.0,0.360000,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_recon0.0_finetune0_temp0.2_eps0.1_sink_itr3_p0.0_v29,0.10,183,0.261429,1.0,1.000000,1.0,0.508571,NaN
swav_ds-s28n_NP700_aff-c5_finetune0_temp0.2_eps0.1_p0.0_v29,0.10,291,0.415714,1.0,1.000000,1.0,0.594286,NaN
swav_ds-s28n_NP700_aff-c4_kl0.0_recon0.0_finetune0_temp0.84_eps0.84_sink_itr3_p0.0_v29,0.84,293,0.418571,1.0,1.000000,1.0,0.320000,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_temp0.2_eps0.1_p0.0_v29,0.10,313,0.447143,1.0,1.000000,1.0,0.582857,NaN
swav_ds-s28n_NP700_aff-c4_kl0.0_finetune0_p0.0_v29,0.05,460,0.657143,1.0,1.000000,1.0,0.605714,NaN
swav_ds-s28n_NP700_aff-c5_kl0.0_finetune0_p0.0_v29,0.05,469,0.670000,1.0,1.000000,1.0,0.582857,NaN

In [32]:
df = dfs['avg_purity_niches_2D'].sort_values('avg', ascending = False)
df = df[df.index.str.contains('swav_ds-s28n_NP700_hard1_aff-c2_lpr0.5_finetune0_temp0.15_sink_itr3_p0.0_laff0.0_v28|seacell')]
df.head(15)

,Macrophage islands,Tumor surface,Tumor core,Desmoplastic stroma,Vascular stroma,Smooth muscle structures,Excluded,T cell aggregates,Alveolar spaces,Airways,avg
seacell,0.412966,0.494449,0.543162,0.433307,0.589201,0.508481,0.27230,0.393425,0.570023,0.960329,0.517764
swav_ds-s28n_NP700_hard1_aff-c2_lpr0.5_finetune0_temp0.15_sink_itr3_p0.0_laff0.0_v28,0.400103,0.491579,0.511865,0.427462,0.564407,0.587273,0.43546,0.440911,0.337600,0.764452,0.496111

In [37]:
df = dfs['stats'].sort_values('unused_proto')
df.head(50)

,epsilon,unused_proto,unused_proto_ratio,cov_niches_2D,cov_celltypes,cov_section,cov_celltypes_niches_2D
swav_ds-s28n_NP700_aff-c_lpr0.5_finetune0_temp0.15_sink_itr3_p0.0_laff0.0_v28,0.02,1,0.001429,1.0,1.0,1.0,0.600000
swav_ds-s28n_NP700_hard1_aff-c_lpr0.5_finetune0_temp0.15_sink_itr3_p0.0_laff0.0_v28,0.02,1,0.001429,1.0,1.0,1.0,0.617143
swav_ds-s28n_NP700_LD16_hard1_aff-c_lpr0.5_finetune0_temp0.15_eps0.1_sink_itr3_p0.0_laff0.0_v28,0.02,3,0.004286,1.0,1.0,1.0,0.571429
swav_ds-s28n_NP700_LD16_aff-c_lpr0.5_finetune0_sink_itr3_p0.0_laff0.0_v28,0.02,3,0.004286,1.0,1.0,1.0,0.565714
swav_ds-s28n_NP700_hard1_aff-c_lpr0.5_finetune0_temp0.15_eps0.1_sink_itr3_p0.0_laff0.0_v28,0.02,3,0.004286,1.0,1.0,1.0,0.617143
swav_ds-s28n_NP700_LD16_aff-c_lpr0.5_finetune0_temp0.15_eps0.1_sink_itr3_p0.0_laff0.0_v28,0.02,3,0.004286,1.0,1.0,1.0,0.565714
swav_ds-s28n_NP700_aff-c_lpr0.5_finetune0_temp0.15_p0.0_laff0.0_v28,0.02,3,0.004286,1.0,1.0,1.0,0.645714
swav_ds-s28n_NP700_LD16_hard1_aff-c_lpr0.5_finetune0_temp0.15_sink_itr3_p0.0_laff0.0_v28,0.02,3,0.004286,1.0,1.0,1.0,0.560000
swav_ds-s28n_NP700_LD16_hard1_aff-c_lpr0.5_finetune0_sink_itr3_p0.0_laff0.0_v28,0.02,4,0.005714,1.0,1.0,1.0,0.560000
swav_ds-s28n_NP700_hard1_aff-c_lpr0.5_finetune0_sink_itr3_p0.0_laff0.0_v28,0.02,4,0.005714,1.0,1.0,1.0,0.588571
swav_ds-s28n_NP700_aff-c_lpr0.5_finetune0_temp0.15_eps0.1_sink_itr3_p0.0_laff0.0_v28,0.02,4,0.005714,1.0,1.0,1.0,0.588571
swav_ds-s28n_NP700_LD16_aff-c_lpr0.5_finetune0_temp0.15_sink_itr3_p0.0_laff0.0_v28,0.02,4,0.005714,1.0,1.0,1.0,0.560000
swav_ds-s28n_NP700_aff-c_lpr0.5_finetune0_sink_itr3_p0.0_laff0.0_v28,0.02,5,0.007143,1.0,1.0,1.0,0.617143
swav_ds-s28n_NP700_hard1_aff-c_lpr0.5_finetune0_temp0.15_p0.0_laff0.0_v28,0.02,5,0.007143,1.0,1.0,1.0,0.651429
swav_ds-s28n_NP700_hard1_aff-c_lpr0.5_finetune0_temp0.15_eps0.1_p0.0_laff0.0_v28,0.02,7,0.010000,1.0,1.0,1.0,0.634286
swav_ds-s28n_NP700_LD16_aff-c_lpr0.5_finetune0_temp0.15_p0.0_laff0.0_v28,0.02,7,0.010000,1.0,1.0,1.0,0.565714
swav_ds-s28n_NP700_LD16_hard1_aff-c_lpr0.5_finetune0_temp0.15_p0.0_laff0.0_v28,0.02,7,0.010000,1.0,1.0,1.0,0.582857
swav_ds-s28n_NP700_aff-c_lpr0.5_finetune0_temp0.15_eps0.1_p0.0_laff0.0_v28,0.02,9,0.012857,1.0,1.0,1.0,0.605714
swav_ds-s28n_NP700_LD16_hard1_aff-c_lpr0.5_finetune0_temp0.15_eps0.1_p0.0_laff0.0_v28,0.02,9,0.012857,1.0,1.0,1.0,0.571429
swav_ds-s28n_NP700_hard1_aff-c2_kl0.0_lpr0.5_finetune0_temp0.15_sink_itr3_p0.0_laff0.0_v28,0.02,9,0.012857,1.0,1.0,1.0,0.622857
swav_ds-s28n_NP700_hard1_aff-c2_lpr0.5_finetune0_temp0.15_sink_itr3_p0.0_laff0.0_v28,0.02,9,0.012857,1.0,1.0,1.0,0.668571
swav_ds-s28n_NP700_LD16_aff-c_lpr0.5_finetune0_temp0.15_eps0.1_p0.0_laff0.0_v28,0.02,10,0.014286,1.0,1.0,1.0,0.565714
swav_ds-s28n_NP700_aff-c2_lpr0.5_finetune0_temp0.15_sink_itr3_p0.0_laff0.0_v28,0.02,10,0.014286,1.0,1.0,1.0,0.668571
swav_ds-s28n_NP700_LD16_aff-c_lpr0.5_finetune0_p0.0_laff0.0_v28,0.02,12,0.017143,1.0,1.0,1.0,0.560000
swav_ds-s28n_NP700_aff-c2_kl0.0_lpr0.5_finetune0_temp0.15_sink_itr3_p0.0_laff0.0_v28,0.02,12,0.017143,1.0,1.0,1.0,0.634286
swav_ds-s28n_NP700_aff-c_lpr0.5_finetune0_p0.0_laff0.0_v28,0.02,13,0.018571,1.0,1.0,1.0,0.617143
swav_ds-s28n_NP700_hard1_aff-c_lpr0.5_finetune0_p0.0_laff0.0_v28,0.02,13,0.018571,1.0,1.0,1.0,0.628571
swav_ds-s28n_NP700_LD16_hard1_aff-c_lpr0.5_finetune0_p0.0_laff0.0_v28,0.02,13,0.018571,1.0,1.0,1.0,0.588571
swav_ds-s28n_NP700_aff-c2_kl0.0_lpr0.5_finetune0_temp0.15_p0.0_laff0.0_v28,0.02,23,0.032857,1.0,1.0,1.0,0.628571
swav_ds-s28n_NP700_hard1_aff-c2_lpr0.5_finetune0_temp0.15_p0.0_laff0.0_v28,0.02,23,0.032857,1.0,1.0,1.0,0.622857
swav_ds-s28n_NP700_aff-c2_lpr0.5_finetune0_temp0.15_p0.0_laff0.0_v28,0.02,24,0.034286,1.0,1.0,1.0,0.622857
swav_ds-s28n_NP700_hard1_aff-c2_kl0.0_lpr0.5_finetune0_temp0.15_p0.0_laff0.0_v28,0.02,25,0.035714,1.0,1.0,1.0,0.611429
swav_ds-s28n_NP700_LD16_aff-sarb_lpr1.0_finetune0_sink_itr3_p0.0_laff0.0_v28,0.02,28,0.040000,1.0,1.0,1.0,0.617143
swav_ds-s28n_NP700_LD32_aff-sarb_lpr1.0_finetune0_p0.0_laff0.0_v27,0.02,35,0.050000,1.0,1.0,1.0,0.605714
swav_ds-s28n_NP700_LD16_aff-sarb_lpr1.0_finetune0_p0.0_laff0.0_v27,0.02,39,0.055714,1.0,1.0,1.0,0.617143
swav_ds-s28n_NP700_LD32_aff-sarb_lpr1.0_finetune0_p0.0_laff0.0_v26,0.02,39,0.055714,1.0,1.0,1.0,0.605714
swav_ds-s28n_NP700_LD16_aff-sarb_lpr1.0_finetune0_p0.0_laff0.0_v26,0.02,40,0.057143,1.0,1.0,1.0,0.594286
swav_ds-s28n_NP700_LD16_aff-sarb_lpr1.0_finetune0_p0.0_laff0.0_v28,0.02,40,0.057143,1.0,1.0,1.0,0.628571
swav_ds-s28n_NP700_aff-c2_finetune0_temp0.15_sink_itr3_p0.0_v29,0.05,94,0.134286,1.0,1.0,1.0,0.645714
swav_ds-s28n_NP700_LD16_aff-sarb_lpr0.5_finetune0_sink_itr3_p0.0_laff0.0_v28,0.02,105,0.150000,1.0,1.0,1.0,0.674286
swav_ds-s28n_NP700_aff-c2_kl0.0_finetune0_temp0.15_sink_itr3_p0.0_v29,0.05,112,0.160000,1.0,1.0,1.0,0.651429
swav_ds-s28n_NP700_LD32_aff-sarb_lpr0.5_finetune0_p0.0_laff0.0_v27,0.02,129,0.184286,1.0,1.0,1.0,0.600000
swav_ds-s28n_NP700_LD16_aff-sarb_lpr0.5_finetune0_p0.0_laff0.0_v27,0.02,130,0.185714,1.0,1.0,1.0,0.628571
swav_ds-s28n_NP700_LD16_aff-sarb_lpr0.5_finetune0_p0.0_laff0.0_v28,0.02,132,0.188571,1.0,1.0,1.0,0.611429
swav_ds-s28n_NP700_LD32_aff-sarb_lpr0.5_finetune0_p0.0_laff0.0_v26,0.02,132,0.188571,1.0,1.0,1.0,0.577143
swav_ds-s28n_NP700_aff-c2_lswav2.0_finetune0_temp0.15_sink_itr3_p0.0_v29,0.05,172,0.245714,1.0,1.0,1.0,0.594286
swav_ds-s28n_NP700_LD16_aff-sarb_lpr0.5_finetune0_p0.0_laff0.0_v26,0.02,173,0.247143,1.0,1.0,1.0,0.628571
swav_ds-s28n_NP700_aff-c2_kl0.0_lswav2.0_finetune0_temp0.15_sink_itr3_p0.0_v29,0.05,183,0.261429,1.0,1.0,1.0,0.600000
swav_ds-s28n_NP700_aff-c2_finetune0_temp0.15_p0.0_v29,0.05,395,0.564286,1.0,1.0,1.0,0.600000
swav_ds-s28n_NP700_aff-c2_kl0.0_finetune0_temp0.15_p0.0_v29,0.05,411,0.587143,1.0,1.0,1.0,0.617143

In [43]:
df = dfs['mc_quality_summary']
df = df.dropna(axis=1, how="all")      # drop columns that are all NaN
df = df.loc[:, (df != 0).any(axis=0)]  # drop columns that are all 0
# df['avg'] = df.mean(axis=1)
df = df[df.index.str.contains('scpoli|aff-c2|seacell')]
# show(df.sort_values('unused_proto'))
df.sort_values('niches_2D_purity_center', ascending=False)

,celltypes_purity_center,celltypes_purity_summary,niches_2D_purity_center,niches_2D_purity_summary,niches_3D_purity_center,niches_3D_purity_summary,fibroblast_subclusters_purity_center,fibroblast_subclusters_purity_summary,fibroblast_subclusters_center,fibroblast_subclusters_summary,EMT_niche_purity_center,EMT_niche_purity_summary,spatial_compactness_center,spatial_compactness_summary,compactness_center,compactness_summary,separation_center,separation_summary,rare_celltypes_purity
seacell,0.840,0.840 ± 0.242,0.514,0.514 ± 0.243,0.492,0.492 ± 0.263,0.933,0.933 ± 0.011,2.0,2.000 ± 2.000,0.945,0.945 ± 0.071,0.587,0.587 ± 0.031,0.006,0.006 ± 0.014,0.024,0.024 ± 0.033,0.835
swav_ds-s28n_NP700_aff-c2_kl0.0_lpr0.5_finetune0_temp0.15_p0.0_laff0.0_v28,0.793,0.793 ± 0.371,0.505,0.505 ± 0.250,0.491,0.491 ± 0.255,0.927,0.927 ± 0.003,2.0,2.000 ± 2.000,0.937,0.937 ± 0.073,0.602,0.602 ± 0.038,0.005,0.005 ± 0.013,0.023,0.023 ± 0.031,0.597
swav_ds-s28n_NP700_aff-c2_lpr0.5_finetune0_temp0.15_p0.0_laff0.0_v28,0.796,0.796 ± 0.350,0.504,0.504 ± 0.260,0.496,0.496 ± 0.254,0.922,0.922 ± 0.012,2.0,2.000 ± 2.000,0.938,0.938 ± 0.074,0.603,0.603 ± 0.040,0.005,0.005 ± 0.012,0.023,0.023 ± 0.029,0.640
swav_ds-s28n_NP700_hard1_aff-c2_kl0.0_lpr0.5_finetune0_temp0.15_p0.0_laff0.0_v28,0.795,0.795 ± 0.360,0.504,0.504 ± 0.245,0.497,0.497 ± 0.236,0.923,0.923 ± 0.010,2.0,2.000 ± 2.000,0.940,0.940 ± 0.077,0.605,0.605 ± 0.038,0.005,0.005 ± 0.012,0.024,0.024 ± 0.028,0.668
swav_ds-s28n_NP700_hard1_aff-c2_lpr0.5_finetune0_temp0.15_p0.0_laff0.0_v28,0.795,0.795 ± 0.368,0.502,0.502 ± 0.256,0.496,0.496 ± 0.258,0.924,0.924 ± 0.010,2.0,2.000 ± 2.000,0.940,0.940 ± 0.075,0.607,0.607 ± 0.038,0.005,0.005 ± 0.012,0.022,0.022 ± 0.030,0.625
swav_ds-s28n_NP700_aff-c2_kl0.0_lpr0.5_finetune0_temp0.15_sink_itr3_p0.0_laff0.0_v28,0.793,0.793 ± 0.364,0.491,0.491 ± 0.232,0.478,0.478 ± 0.243,0.919,0.919 ± 0.026,2.0,2.000 ± 2.000,0.938,0.938 ± 0.078,0.601,0.601 ± 0.031,0.006,0.006 ± 0.014,0.024,0.024 ± 0.030,0.535
swav_ds-s28n_NP700_hard1_aff-c2_lpr0.5_finetune0_temp0.15_sink_itr3_p0.0_laff0.0_v28,0.793,0.793 ± 0.360,0.488,0.488 ± 0.246,0.477,0.477 ± 0.239,0.917,0.917 ± 0.033,2.0,2.000 ± 2.000,0.938,0.938 ± 0.079,0.598,0.598 ± 0.035,0.006,0.006 ± 0.013,0.024,0.024 ± 0.031,0.569
swav_ds-s28n_NP700_hard1_aff-c2_kl0.0_lpr0.5_finetune0_temp0.15_sink_itr3_p0.0_laff0.0_v28,0.791,0.791 ± 0.362,0.487,0.487 ± 0.248,0.476,0.476 ± 0.242,0.917,0.917 ± 0.027,2.0,2.000 ± 2.000,0.937,0.937 ± 0.077,0.597,0.597 ± 0.033,0.006,0.006 ± 0.014,0.024,0.024 ± 0.032,0.542
swav_ds-s28n_NP700_aff-c2_lpr0.5_finetune0_temp0.15_sink_itr3_p0.0_laff0.0_v28,0.793,0.793 ± 0.358,0.487,0.487 ± 0.245,0.480,0.480 ± 0.244,0.918,0.918 ± 0.026,2.0,2.000 ± 2.000,0.938,0.938 ± 0.077,0.599,0.599 ± 0.034,0.006,0.006 ± 0.014,0.024,0.024 ± 0.030,0.533
scpoli_ds-s28n_NP700_lswav0.0_finetune0_laff0.0_v23,0.782,0.782 ± 0.344,0.466,0.466 ± 0.209,0.458,0.458 ± 0.223,0.897,0.897 ± 0.093,2.0,2.000 ± 2.000,0.938,0.938 ± 0.069,0.589,0.589 ± 0.027,0.008,0.008 ± 0.018,0.024,0.024 ± 0.029,0.664
scpoli_ds-s28n_NP700_lswav0.0_finetune0_laff0.0_v24,0.774,0.774 ± 0.343,0.453,0.453 ± 0.203,0.443,0.443 ± 0.203,0.893,0.893 ± 0.104,2.0,2.000 ± 2.000,0.939,0.939 ± 0.066,0.591,0.591 ± 0.026,0.008,0.008 ± 0.017,0.025,0.025 ± 0.029,0.588

In [38]:
df[df.index.str.contains('scpoli')]

,celltypes_purity_center,celltypes_purity_summary,niches_2D_purity_center,niches_2D_purity_summary,niches_3D_purity_center,niches_3D_purity_summary,fibroblast_subclusters_purity_center,fibroblast_subclusters_purity_summary,fibroblast_subclusters_center,fibroblast_subclusters_summary,EMT_niche_purity_center,EMT_niche_purity_summary,spatial_compactness_center,spatial_compactness_summary,compactness_center,compactness_summary,separation_center,separation_summary,rare_celltypes_purity
scpoli_ds-s28n_NP700_lswav0.0_finetune0_laff0.0_v23,0.782,0.782 ± 0.344,0.466,0.466 ± 0.209,0.458,0.458 ± 0.223,0.897,0.897 ± 0.093,2.0,2.000 ± 2.000,0.938,0.938 ± 0.069,0.589,0.589 ± 0.027,0.008,0.008 ± 0.018,0.024,0.024 ± 0.029,0.664
scpoli_ds-s28n_NP700_lswav0.0_finetune0_laff0.0_v24,0.774,0.774 ± 0.343,0.453,0.453 ± 0.203,0.443,0.443 ± 0.203,0.893,0.893 ± 0.104,2.0,2.000 ± 2.000,0.939,0.939 ± 0.066,0.591,0.591 ± 0.026,0.008,0.008 ± 0.017,0.025,0.025 ± 0.029,0.588

In [21]:
df = dfs['stats']
df = df.dropna(axis=1, how="all")      # drop columns that are all NaN
df = df.loc[:, (df != 0).any(axis=0)]  # drop columns that are all 0
df['avg'] = df.mean(axis=1)
df = df[df.index.str.contains('scpoli|aff-c|seacell')]
show(df.sort_values('unused_proto'))
# show(df.sort_values('avg', ascending = False))